---
title: "Project Assignment 1"
subtitle: "Research Question and Data Sources"
---

## Overview

For this project you will work in groups to use data to answer a question. This is your chance to use the skills you are developing in this class to help guide decision-making in a real-world context. 

Crucially, your data analysis should be question-driven. Part of the challenge is to identify the most appropriate data and analysis to answer your question. You will need to think about how to do this and the answer will not always be obvious--a level of creativity is involved. 

For this first project assignment, you are to form groups of 3-4 students. You will select a question to work on, do some preliminary research on the type of data that might help you to answer the question, and discuss how you will use the data to provide an answer.

## Groups

You will form groups of 3-4 students. You will work with this group for the duration of the project. Please list the names of your group members here:

Liam Robins

Fazilat Khaydarkhonova

Raphael Pierron-Darbonne

Ben Akyureklier

## Topics

You should select from the following list of topics. If you have another topic in mind, please discuss with me before proceeding. After choosing your topic, delete the other non-chosen topics and discuss briefly why you chose it. 

- As a consultant for the World Bank, you are tasked with improving democratic governance in developing countries. Based on trends in political and economic data over the past decade, what key areas (e.g., electoral integrity, gender equity, economic policy) should you prioritize to enhance democracy?
- We are interested in investigating how different social and economic factors affect democracy around the globe. Additionally, we are interested in testing which factors, whether more social/political (gender equality, violence), or more economic (economic freedom, inequality) in nature, have the biggest effect.


## Hypotheses

Before gathering any data, or even looking at any data, you should write down your hypotheses. These are the assumptions you are making about the world that you will test with your data. Or, another way to think about hypotheses is as the predicted relationships between variables that you will test with your data. What do you **expect** to find and how do you **expect** the variables to be related? Write these down in a list here.

- H1: Democracy is more strongly correlated with economic development than it is with gender equality.
- H2: Countries with lower levels of economic inequality tend to be more democratic.
- H3: Countries with greater economic freedom tend to be more democratic.
- H4: Countries with less history of violence/terrorism tend to be more democratic.

## Data Sources

Now it is time to identify your data sources. You can use any data source that will be relevant in answering your question. This could be data from a government agency, an international organization, a non-profit, a private company, or even data that you collect yourself. A partial list of data sources is available [here](project-datasets.qmd). 

Briefly list and discuss the data sources you plan to use. What data do they contain? How will you use them to answer your question? I would limit the number of data sources to 2-3. But just one data source is also OK if you think it is sufficient to answer your question.

- Data Source 1: Varieties of Democracy (V-DEM)
- Publishes measures of democracy for countries around the world and over time. This includes:
	-Electoral democracy index
-Liberal democracy index
	-Participatory democracy index
	-Deliberative democracy index
- We’ll treat these as our dependent variables.
- We plan to run regressions between these indices and several variables from the World Bank to see which variables are most strongly correlated with democracy.
- https://v-dem.net/documents/41/v-dem_structureofaggregation_v14.pdf

- Data Source 2: World Bank; 
- The World Bank publishes indicators for most countries in the world, mostly on topics of economics but also on subjects like democracy and governance. For example:
- Their World Development Indicators database has indicators for hundreds of measures of economic development, including percentage of a country’s population living below the international poverty line, GINI coefficient (which measures economic inequality), and percentage of a country’s population with access to basic services like electricity.
- Their Worldwide Governance Indicators database has indicators for six dimensions of governance: Voice and Accountability; Political Stability and Absence of Violence/Terrorism; Government Effectiveness; Regulatory Quality; Rule of Law; Control of Corruption.
-v2clgencl (Gender equality in respect for civil liberties)
-Gini index (Poverty and Inequality Platform)
- We’ll treat these as our independent variables.
- We plan to run regressions between these indices and several variables from the World Bank to see which variables are most strongly correlated with democracy.

## Submission

*That is it for Project Assignment 1! Please export this document and submit it via Blackboard by the due date. Each student should submit a separate QMD file so that we have something in Blackboard to grade.*
